# fly.toml app configuration file generated for questify-worker on 2025-09-21T15:21:54-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'questify-worker'
primary_region = 'yyz'

[build]
  dockerfile = "Dockerfile"
